-- MySQL Script generated by MySQL Workbench
-- Wed Jul 24 16:31:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema StoreApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StoreApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StoreApp` DEFAULT CHARACTER SET utf8 ;
USE `StoreApp` ;

-- -----------------------------------------------------
-- Table `StoreApp`.`Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Perfiles` (
  `idPerfiles` INT NOT NULL,
  `perfil` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idPerfiles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `usuname` VARCHAR(45) NULL,
  `nombre` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  `idperfil` INT NULL,
  `estado` INT NULL,
  `Perfiles_idPerfiles` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Perfiles_idx` (`Perfiles_idPerfiles` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Perfiles`
    FOREIGN KEY (`Perfiles_idPerfiles`)
    REFERENCES `StoreApp`.`Perfiles` (`idPerfiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`SubZonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`SubZonas` (
  `idSubZonas` INT NOT NULL,
  `idzona` INT NULL,
  `subzona` VARCHAR(100) NULL,
  PRIMARY KEY (`idSubZonas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Zonas` (
  `idZonas` INT NOT NULL,
  `zona` VARCHAR(45) NULL,
  `SubZonas_idSubZonas` INT NOT NULL,
  PRIMARY KEY (`idZonas`),
  INDEX `fk_Zonas_SubZonas1_idx` (`SubZonas_idSubZonas` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_SubZonas1`
    FOREIGN KEY (`SubZonas_idSubZonas`)
    REFERENCES `StoreApp`.`SubZonas` (`idSubZonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`ZonasDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`ZonasDetalle` (
  `idZona` INT NOT NULL,
  `idUsuario` INT NULL,
  `estado` INT NULL,
  `Zonas_idZonas` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idZona`),
  INDEX `fk_ZonasDetalle_Zonas1_idx` (`Zonas_idZonas` ASC) VISIBLE,
  INDEX `fk_ZonasDetalle_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_ZonasDetalle_Zonas1`
    FOREIGN KEY (`Zonas_idZonas`)
    REFERENCES `StoreApp`.`Zonas` (`idZonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZonasDetalle_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `StoreApp`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`TiposCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`TiposCliente` (
  `idTiposCliente` INT NOT NULL,
  `Tiposcliente` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idTiposCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Clientes` (
  `idClientes` INT NOT NULL,
  `idtipocliente` INT NULL,
  `identidad` VARCHAR(45) NULL,
  `rtncliente` VARCHAR(20) NULL,
  `nombrecliente` VARCHAR(50) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `idsubzona` INT NULL,
  `SubZonas_idSubZonas` INT NOT NULL,
  `TiposCliente_idTiposCliente` INT NOT NULL,
  PRIMARY KEY (`idClientes`, `SubZonas_idSubZonas`, `TiposCliente_idTiposCliente`),
  INDEX `fk_Clientes_SubZonas1_idx` (`SubZonas_idSubZonas` ASC) VISIBLE,
  INDEX `fk_Clientes_TiposCliente1_idx` (`TiposCliente_idTiposCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_SubZonas1`
    FOREIGN KEY (`SubZonas_idSubZonas`)
    REFERENCES `StoreApp`.`SubZonas` (`idSubZonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_TiposCliente1`
    FOREIGN KEY (`TiposCliente_idTiposCliente`)
    REFERENCES `StoreApp`.`TiposCliente` (`idTiposCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`TipoFacturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`TipoFacturas` (
  `idTipoFactura` INT NOT NULL,
  `TipoFactura` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Plazos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Plazos` (
  `idPlan` INT NOT NULL,
  `nummeses` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`ParametrosGenerales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`ParametrosGenerales` (
  `codempresa` VARCHAR(20) NOT NULL,
  `rtn` VARCHAR(20) NULL,
  `denominacionsocial` VARCHAR(150) NULL,
  PRIMARY KEY (`codempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Facturas` (
  `numfactura` INT NULL,
  `codempresa` VARCHAR(45) NULL,
  `idtipofactura` INT NULL,
  `idcliente` INT NULL,
  `idvendedor` INT NULL,
  `idsupervisor` INT NULL,
  `fecha` DATE NULL,
  `idplan` INT NULL,
  `subtotal` DECIMAL(18,2) NULL,
  `isv` DECIMAL(18,2) NULL,
  `abono` DECIMAL(18,2) NULL,
  `saldo` DECIMAL(18,2) NULL,
  `estado` INT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Clientes_SubZonas_idSubZonas` INT NOT NULL,
  `Clientes_TiposCliente_idTiposCliente` INT NOT NULL,
  `TipoFacturas_idTipoFactura` INT NOT NULL,
  `Plazos_idPlan` INT NOT NULL,
  `ParametrosGenerales_codempresa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`numfactura`, `Clientes_idClientes`, `Clientes_SubZonas_idSubZonas`, `Clientes_TiposCliente_idTiposCliente`),
  UNIQUE INDEX `numfactura_UNIQUE` (`numfactura` ASC) VISIBLE,
  INDEX `fk_Facturas_Clientes1_idx` (`Clientes_idClientes` ASC, `Clientes_SubZonas_idSubZonas` ASC, `Clientes_TiposCliente_idTiposCliente` ASC) VISIBLE,
  INDEX `fk_Facturas_TipoFacturas1_idx` (`TipoFacturas_idTipoFactura` ASC) VISIBLE,
  INDEX `fk_Facturas_Plazos1_idx` (`Plazos_idPlan` ASC) VISIBLE,
  INDEX `fk_Facturas_ParametrosGenerales1_idx` (`ParametrosGenerales_codempresa` ASC) VISIBLE,
  CONSTRAINT `fk_Facturas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes` , `Clientes_SubZonas_idSubZonas` , `Clientes_TiposCliente_idTiposCliente`)
    REFERENCES `StoreApp`.`Clientes` (`idClientes` , `SubZonas_idSubZonas` , `TiposCliente_idTiposCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_TipoFacturas1`
    FOREIGN KEY (`TipoFacturas_idTipoFactura`)
    REFERENCES `StoreApp`.`TipoFacturas` (`idTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Plazos1`
    FOREIGN KEY (`Plazos_idPlan`)
    REFERENCES `StoreApp`.`Plazos` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_ParametrosGenerales1`
    FOREIGN KEY (`ParametrosGenerales_codempresa`)
    REFERENCES `StoreApp`.`ParametrosGenerales` (`codempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`DetalleFactura` (
  `numfactura` INT NOT NULL,
  `idproducto` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `primacobrada` DECIMAL(18,2) NULL,
  `precioventa` DECIMAL(18,2) NULL,
  `Facturas_numfactura` INT NOT NULL,
  `Facturas_Clientes_idClientes` INT NOT NULL,
  `Facturas_Clientes_SubZonas_idSubZonas` INT NOT NULL,
  `Facturas_Clientes_TiposCliente_idTiposCliente` INT NOT NULL,
  PRIMARY KEY (`numfactura`),
  INDEX `fk_DetalleFactura_Facturas1_idx` (`Facturas_numfactura` ASC, `Facturas_Clientes_idClientes` ASC, `Facturas_Clientes_SubZonas_idSubZonas` ASC, `Facturas_Clientes_TiposCliente_idTiposCliente` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleFactura_Facturas1`
    FOREIGN KEY (`Facturas_numfactura` , `Facturas_Clientes_idClientes` , `Facturas_Clientes_SubZonas_idSubZonas` , `Facturas_Clientes_TiposCliente_idTiposCliente`)
    REFERENCES `StoreApp`.`Facturas` (`numfactura` , `Clientes_idClientes` , `Clientes_SubZonas_idSubZonas` , `Clientes_TiposCliente_idTiposCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Productos` (
  `idProductos` INT NOT NULL,
  `producto` VARCHAR(100) NULL,
  `descripcion` VARCHAR(200) NULL,
  `precosto` DECIMAL(18,2) NULL,
  `precontado` DECIMAL(18,2) NULL,
  `precredito` DECIMAL(18,2) NULL,
  `preprima` DECIMAL(18,2) NULL,
  `premayorista` DECIMAL(18,2) NULL,
  `estado` INT NULL,
  `DetalleFactura_numfactura` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `DetalleFactura_numfactura`),
  INDEX `fk_Productos_DetalleFactura1_idx` (`DetalleFactura_numfactura` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_DetalleFactura1`
    FOREIGN KEY (`DetalleFactura_numfactura`)
    REFERENCES `StoreApp`.`DetalleFactura` (`numfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`Inventario` (
  `idProducto` INT NOT NULL,
  `cantidad` INT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Inventario_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `StoreApp`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`ControlPagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`ControlPagos` (
  `idPago` INT NOT NULL,
  `numfactura` INT NULL,
  `cuota` INT NULL,
  `numcuotarest` INT NULL,
  `fechapago` DATE NULL,
  `saldoanterior` DECIMAL(18,2) NULL,
  `abono` DECIMAL(18,2) NULL,
  `saldoactual` DECIMAL(18,2) NULL,
  `Facturas_numfactura` INT NOT NULL,
  `Facturas_Clientes_idClientes` INT NOT NULL,
  `Facturas_Clientes_SubZonas_idSubZonas` INT NOT NULL,
  `Facturas_Clientes_TiposCliente_idTiposCliente` INT NOT NULL,
  PRIMARY KEY (`idPago`, `Facturas_numfactura`, `Facturas_Clientes_idClientes`, `Facturas_Clientes_SubZonas_idSubZonas`, `Facturas_Clientes_TiposCliente_idTiposCliente`),
  INDEX `fk_ControlPagos_Facturas1_idx` (`Facturas_numfactura` ASC, `Facturas_Clientes_idClientes` ASC, `Facturas_Clientes_SubZonas_idSubZonas` ASC, `Facturas_Clientes_TiposCliente_idTiposCliente` ASC) VISIBLE,
  CONSTRAINT `fk_ControlPagos_Facturas1`
    FOREIGN KEY (`Facturas_numfactura` , `Facturas_Clientes_idClientes` , `Facturas_Clientes_SubZonas_idSubZonas` , `Facturas_Clientes_TiposCliente_idTiposCliente`)
    REFERENCES `StoreApp`.`Facturas` (`numfactura` , `Clientes_idClientes` , `Clientes_SubZonas_idSubZonas` , `Clientes_TiposCliente_idTiposCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`DetallePagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`DetallePagos` (
  `idDetallePago` INT NOT NULL,
  `idpago` INT NULL,
  `idcolaborador` INT NULL,
  `fechaabono` DATE NULL,
  `abono` DECIMAL(18,2) NULL,
  `nummes` INT NULL,
  `DetallePagoscol` VARCHAR(45) NULL,
  `ControlPagos_idPago` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idDetallePago`, `ControlPagos_idPago`, `Usuarios_idUsuarios`),
  INDEX `fk_DetallePagos_ControlPagos1_idx` (`ControlPagos_idPago` ASC) VISIBLE,
  INDEX `fk_DetallePagos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_DetallePagos_ControlPagos1`
    FOREIGN KEY (`ControlPagos_idPago`)
    REFERENCES `StoreApp`.`ControlPagos` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePagos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `StoreApp`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StoreApp`.`DetalleFacturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StoreApp`.`DetalleFacturacion` (
  `idDetalleFacturacion` INT NOT NULL,
  `codempresa` VARCHAR(45) NULL,
  `facturaini` DATE NULL,
  `facturafinal` DATE NULL,
  `fechalimiteemicion` DATE NULL,
  `kai` VARCHAR(45) NULL,
  `estado` INT NULL,
  `ParametrosGenerales_codempresa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idDetalleFacturacion`),
  INDEX `fk_DetalleFacturacion_ParametrosGenerales1_idx` (`ParametrosGenerales_codempresa` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleFacturacion_ParametrosGenerales1`
    FOREIGN KEY (`ParametrosGenerales_codempresa`)
    REFERENCES `StoreApp`.`ParametrosGenerales` (`codempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
